// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransjapHorimetros.Infrastructure.Persistence;

#nullable disable

namespace TransjapHorimetros.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransjapDbContext))]
    partial class TransjapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransjapHorimetros.Domain.Entities.Anomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("ReadingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reading_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_anomalies");

                    b.HasIndex("ReadingId")
                        .HasDatabaseName("ix_anomalies_reading_id");

                    b.ToTable("anomalies", (string)null);
                });

            modelBuilder.Entity("TransjapHorimetros.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("action");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("entity_id");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("Entity", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TransjapHorimetros.Domain.Entities.HourMeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturedAtDevice")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("captured_at_device");

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("client_event_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("machine_id");

                    b.Property<string>("ReadingType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("reading_type");

                    b.Property<DateTime>("ReceivedAtServer")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("received_at_server");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("synced_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("value");

                    b.Property<Guid?>("WorkSiteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_site_id");

                    b.HasKey("Id")
                        .HasName("pk_hour_meter_readings");

                    b.HasIndex("ClientEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_hour_meter_readings_client_event_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_hour_meter_readings_status");

                    b.HasIndex("WorkSiteId")
                        .HasDatabaseName("ix_hour_meter_readings_work_site_id");

                    b.HasIndex("MachineId", "CapturedAtDevice")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_hour_meter_readings_machine_captured_at");

                    b.ToTable("hour_meter_readings", null, t =>
                        {
                            t.HasCheckConstraint("ck_hour_meter_readings_value_non_negative", "value >= 0");
                        });
                });

            modelBuilder.Entity("TransjapHorimetros.Domain.Entities.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("created_at");

                    b.Property<int>("FleetNumber")
                        .HasColumnType("int")
                        .HasColumnName("fleet_number");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("model");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_machines");

                    b.HasIndex("FleetNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_machines_fleet_number");

                    b.ToTable("machines", null, t =>
                        {
                            t.HasCheckConstraint("ck_machines_fleet_number_positive", "fleet_number > 0");
                        });
                });

            modelBuilder.Entity("TransjapHorimetros.Domain.Entities.WorkSite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_work_sites");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_work_sites_code");

                    b.ToTable("work_sites", (string)null);
                });

            modelBuilder.Entity("TransjapHorimetros.Domain.Entities.Anomaly", b =>
                {
                    b.HasOne("TransjapHorimetros.Domain.Entities.HourMeterReading", "Reading")
                        .WithMany("Anomalies")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_anomalies_hour_meter_readings_reading_id");

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("TransjapHorimetros.Domain.Entities.HourMeterReading", b =>
                {
                    b.HasOne("TransjapHorimetros.Domain.Entities.Machine", "Machine")
                        .WithMany("Readings")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hour_meter_readings_machines_machine_id");

                    b.HasOne("TransjapHorimetros.Domain.Entities.WorkSite", "WorkSite")
                        .WithMany("Readings")
                        .HasForeignKey("WorkSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_hour_meter_readings_work_sites_work_site_id");

                    b.Navigation("Machine");

                    b.Navigation("WorkSite");
                });

            modelBuilder.Entity("TransjapHorimetros.Domain.Entities.HourMeterReading", b =>
                {
                    b.Navigation("Anomalies");
                });

            modelBuilder.Entity("TransjapHorimetros.Domain.Entities.Machine", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("TransjapHorimetros.Domain.Entities.WorkSite", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
